server:
  port: 81

spring:
  application:
    name: customer-fundcrawler
    #  eureka:
    #    client:
    #      register-with-eureka: true
    #      #    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    #      #    fetch-registry: true
    #      service-url:
    #        # 入驻地址
    #        defaultZone: http://localhost:7001/eureka/
    #      #集群版
    #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    #  #服务名称
    #  instance:
    #    instance-id: payment8001
    #    #访问路径显示IP地址
    #    prefer-ip-address: true

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: customer-fundcrawler81
    prefer-ip-address: true